# Generated by Django 5.0.6 on 2024-05-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_balance_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payer',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Equal', 'Equal')], max_length=10),
        ),
    ]
